baseURL = "https://frosty-perlman-43ebf9.netlify.app/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-PaperMod-master"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.74.3"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.74.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[menu.main]]
name = "Introduction"
weight = 1
url = "/introduction/"

[[menu.main]]
name = "Dummy Annotated Definations"
weight = 2
url = "/dummyannotateddefinitions/"

[[menu.main]]
name = "Dummy Resoure Guide"
weight = 1
url = "/dummyresourceguide/"

[[menu.main]]
name = "Dummy Walkthrough"
weight = 1
url = "/dummywalkthough/"
